# Generated by Django 2.2.24 on 2021-06-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
