# Generated by Django 2.2.24 on 2021-06-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_field',
        ),
    ]
