# Generated by Django 3.2 on 2021-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210606_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='home_university',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='motivation',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_network_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
