# Generated by Django 3.2 on 2021-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210606_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='motivation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_network_account',
            field=models.CharField(max_length=100),
        ),
    ]
