# Generated by Django 3.2 on 2021-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210606_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
